// This file is @generated by prost-build.
/// A trading account to connect to.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Account {
    /// "MT4" or "MT5".
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub user: u64,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub server: ::prost::alloc::string::String,
    /// Optional display name; the server generates one if this is empty.
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    /// Optional terminal session id if already connected via ConnectEx
    #[prost(string, tag = "6")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartRequest {
    /// The caller's key. It is both the user the copier belongs to and the manager creating it —
    /// a self-service copier has the customer acting as their own manager.
    #[prost(string, tag = "1")]
    pub user_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub manager_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub master: ::core::option::Option<Account>,
    #[prost(message, optional, tag = "4")]
    pub slave: ::core::option::Option<Account>,
    /// FixedLot | LotMultiplier | BalanceMultiplier | FixedBalanceMultiplier | EquityMultiplier
    #[prost(string, tag = "5")]
    pub risk_type: ::prost::alloc::string::String,
    /// decimal as a string: a double would round money
    #[prost(string, tag = "6")]
    pub risk_value: ::prost::alloc::string::String,
    /// required when risk_type is FixedBalanceMultiplier
    #[prost(string, tag = "7")]
    pub fixed_master_balance: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub copy_sl: bool,
    #[prost(bool, tag = "9")]
    pub copy_tp: bool,
    #[prost(bool, tag = "10")]
    pub copy_pending_orders: bool,
    #[prost(bool, tag = "11")]
    pub reverse_copy: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartReply {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub copier_id: ::prost::alloc::string::String,
    /// Set when ok is false. REST reports failure as HTTP 201 with an error body; gRPC does not
    /// inherit that, so a failed start is ok=false with a message the caller can show.
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRequest {
    #[prost(string, tag = "1")]
    pub user_key: ::prost::alloc::string::String,
}
/// What a copier looks like to whoever is allowed to see it.
///
/// Deliberately NOT the full stored record. That record contains MasterPassword and SlavePassword,
/// and the REST /UserCopiers returns them in full — so every consumer has had to remember to strip
/// them. There is nowhere to put them here, which makes the safe outcome the default one.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CopierSummary {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub master_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub master_user: u64,
    #[prost(string, tag = "4")]
    pub master_server: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub slave_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub slave_user: u64,
    #[prost(string, tag = "7")]
    pub slave_server: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub risk_type: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub risk_value: ::prost::alloc::string::String,
    #[prost(bool, tag = "10")]
    pub paused: bool,
    /// Why it is paused, when it is. "Paused" on its own cannot tell a customer that the account
    /// their copier followed was deleted, and that is exactly the case they most need to see.
    #[prost(string, tag = "11")]
    pub pause_reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReply {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(message, repeated, tag = "2")]
    pub copiers: ::prost::alloc::vec::Vec<CopierSummary>,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseRequest {
    #[prost(string, tag = "1")]
    pub user_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub copier_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub paused: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRequest {
    #[prost(string, tag = "1")]
    pub user_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub copier_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SimpleReply {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod copier_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Trade copier operations over gRPC.
    ///
    /// This exists for one reason: the REST equivalents take the master's and slave's MT account
    /// PASSWORDS as query parameters. A query string is written to the ingress log, to any proxy in
    /// between, and to the browser's history — so every copier ever started has put two sets of live
    /// trading credentials into plain-text logs. gRPC carries them in the request body over HTTP/2,
    /// where nothing on the path records them.
    ///
    /// The REST endpoints are untouched and still serve copyfront. This is an additional transport for
    /// the same operations, not a replacement, and it delegates to exactly the same implementation so
    /// the two cannot drift.
    #[derive(Debug, Clone)]
    pub struct CopierServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CopierServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CopierServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CopierServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CopierServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Start a copier. The only call that carries credentials.
        pub async fn start(
            &mut self,
            request: impl tonic::IntoRequest<super::StartRequest>,
        ) -> std::result::Result<tonic::Response<super::StartReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/copier.CopierService/Start",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("copier.CopierService", "Start"));
            self.inner.unary(req, path, codec).await
        }
        /// Every copier belonging to a user. Never returns stored passwords — see CopierSummary.
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/copier.CopierService/List",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("copier.CopierService", "List"));
            self.inner.unary(req, path, codec).await
        }
        /// Pause or resume.
        pub async fn pause(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::SimpleReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/copier.CopierService/Pause",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("copier.CopierService", "Pause"));
            self.inner.unary(req, path, codec).await
        }
        /// Remove a copier.
        pub async fn remove(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveRequest>,
        ) -> std::result::Result<tonic::Response<super::SimpleReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/copier.CopierService/Remove",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("copier.CopierService", "Remove"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod copier_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CopierServiceServer.
    #[async_trait]
    pub trait CopierService: std::marker::Send + std::marker::Sync + 'static {
        /// Start a copier. The only call that carries credentials.
        async fn start(
            &self,
            request: tonic::Request<super::StartRequest>,
        ) -> std::result::Result<tonic::Response<super::StartReply>, tonic::Status>;
        /// Every copier belonging to a user. Never returns stored passwords — see CopierSummary.
        async fn list(
            &self,
            request: tonic::Request<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListReply>, tonic::Status>;
        /// Pause or resume.
        async fn pause(
            &self,
            request: tonic::Request<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::SimpleReply>, tonic::Status>;
        /// Remove a copier.
        async fn remove(
            &self,
            request: tonic::Request<super::RemoveRequest>,
        ) -> std::result::Result<tonic::Response<super::SimpleReply>, tonic::Status>;
    }
    /// Trade copier operations over gRPC.
    ///
    /// This exists for one reason: the REST equivalents take the master's and slave's MT account
    /// PASSWORDS as query parameters. A query string is written to the ingress log, to any proxy in
    /// between, and to the browser's history — so every copier ever started has put two sets of live
    /// trading credentials into plain-text logs. gRPC carries them in the request body over HTTP/2,
    /// where nothing on the path records them.
    ///
    /// The REST endpoints are untouched and still serve copyfront. This is an additional transport for
    /// the same operations, not a replacement, and it delegates to exactly the same implementation so
    /// the two cannot drift.
    #[derive(Debug)]
    pub struct CopierServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CopierServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CopierServiceServer<T>
    where
        T: CopierService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/copier.CopierService/Start" => {
                    #[allow(non_camel_case_types)]
                    struct StartSvc<T: CopierService>(pub Arc<T>);
                    impl<
                        T: CopierService,
                    > tonic::server::UnaryService<super::StartRequest> for StartSvc<T> {
                        type Response = super::StartReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StartRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CopierService>::start(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/copier.CopierService/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: CopierService>(pub Arc<T>);
                    impl<
                        T: CopierService,
                    > tonic::server::UnaryService<super::ListRequest> for ListSvc<T> {
                        type Response = super::ListReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CopierService>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/copier.CopierService/Pause" => {
                    #[allow(non_camel_case_types)]
                    struct PauseSvc<T: CopierService>(pub Arc<T>);
                    impl<
                        T: CopierService,
                    > tonic::server::UnaryService<super::PauseRequest> for PauseSvc<T> {
                        type Response = super::SimpleReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PauseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CopierService>::pause(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PauseSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/copier.CopierService/Remove" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveSvc<T: CopierService>(pub Arc<T>);
                    impl<
                        T: CopierService,
                    > tonic::server::UnaryService<super::RemoveRequest>
                    for RemoveSvc<T> {
                        type Response = super::SimpleReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CopierService>::remove(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CopierServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "copier.CopierService";
    impl<T> tonic::server::NamedService for CopierServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
